INSERT INTO produto (ID_prod,nome, tamanho ,marca ,tipoMedida,possui_ID_prod )
VALUES (1,  'Banana', 			     NULL,	NULL, 		 'kg',	 NULL),
	   (2,  'Coca Cola', 		     300, 	NULL, 		 'ml',	 NULL),
	   (3,  'Coca Cola', 		     600, 	NULL, 		 'ml',	 NULL),
	   (4,  'Coca Cola', 		     2, 	NUll, 		 'l',	 NULL),
	   (5,  'Arroz', 			     1, 	'sepó', 	 'kg',	 NULL),
	   (6,  'Feijao', 			     2, 	'sabugo', 	 'kg',	 NULL),
	   (7,  'Milho', 			     1, 	'sadiga', 	 'kg',	 NULL),
	   (8,  'Escova de dente', 	     10, 	'Lonis', 	 'cm',	 NULL),
	   (9,  'Copos de plastico',     300, 	'Nanis', 	 'ml',	 NULL),
	   (10, 'Pendrive', 		     8, 	'Kingspon',	 'gb',	 NULL),
	   (11, 'Barra de chocolate',    200, 	'maroto', 	 'g',	 NULL),
	   (12, 'Lãmpada LED', 		     6, 	'lapda', 	 'watt', NULL),
	   (13, 'Lâmpada Incandescente', 40, 	'lapda', 	 'watt', NULL),
	   (14, 'Trigo', 			     1, 	'felizardo', 'kg',	 NULL),
	   (15, 'Biscoito recheado', 	 100, 	'Prakinas',  'g',	 NULL),
	   (16, 'Batata chips', 		 75, 	'Muffles', 	 'g',	 NULL),
	   (17, 'Detergente', 		     500, 	'Limol', 	 'ml',	 NULL),
	   (18, 'Par de Chinelos', 	     NULL, 	'Cavaibana', NULL,	 NULL),
	   (19, 'Carne picanha', 		 1, 	NULL, 		 'kg',	 NULL),
	   (20, 'Pacote de lenço', 	     NULL, 	'glinex', 	 NULL,	 NULL);
